/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.Response
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DevelopersApi {

  /**
   * 
   * 
   * Expected answers:
   *   code 200 : Response (search results matching criteria)
   *   code 400 :  (bad input parameter)
   */
  def searchInventory my spec(): ApiRequest[Response] =
    ApiRequest[Response](ApiMethods.GET, "https://virtserver.swaggerhub.com/SmartBear-CC/APIToMerge1/1.0.0", "/inventory", "application/json")
      .withSuccessResponse[Response](200)
      .withErrorResponse[Unit](400)
      

}

