export * from './actionInstances.service';
import { ActionInstancesService } from './actionInstances.service';
export * from './actionMetadata.service';
import { ActionMetadataService } from './actionMetadata.service';
export * from './channels.service';
import { ChannelsService } from './channels.service';
export * from './configuration.service';
import { ConfigurationService } from './configuration.service';
export * from './domains.service';
import { DomainsService } from './domains.service';
export * from './metadataImport.service';
import { MetadataImportService } from './metadataImport.service';
export * from './recommendations.service';
import { RecommendationsService } from './recommendations.service';
export * from './selections.service';
import { SelectionsService } from './selections.service';
export * from './strategies.service';
import { StrategiesService } from './strategies.service';
export * from './subjectMetadata.service';
import { SubjectMetadataService } from './subjectMetadata.service';
export * from './tags.service';
import { TagsService } from './tags.service';
export * from './tenants.service';
import { TenantsService } from './tenants.service';
export const APIS = [ActionInstancesService, ActionMetadataService, ChannelsService, ConfigurationService, DomainsService, MetadataImportService, RecommendationsService, SelectionsService, StrategiesService, SubjectMetadataService, TagsService, TenantsService];
