/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DomainId } from './domainId';
import { ItemBase } from './itemBase';


export interface ActionBase extends ItemBase {
    /**
     * ID of the Domain in which the item exists.
     */
    domainId?: string;
    /**
     * JSON object contianing the action instance. For example, this might represent a Campaign Activity or a Communication Type. 
     */
    actionDefinition?: any;
    /**
     * Collection of Channels that the Action may be presented on
     */
    channels?: Array<string>;
    /**
     * Status of the Action.
     */
    status?: ActionBase.StatusEnum;
    /**
     * Priority of the Action
     */
    priority?: number;
    /**
     * Collection of Tags associated with the Action
     */
    tags?: Array<string>;
    /**
     * Date and time representing when the action starts to become available. If not specified the action is available from the start of time. 
     */
    availableFrom?: string;
    /**
     * Date and time representing when the action stops being available. If not specified the action is available until the end of time.  
     */
    availableTo?: string;
    /**
     * Name of a score that will be associated with this Action if it is passed into the runtime getRecommendations operation. 
     */
    scoreName?: string;
    /**
     * Value of the score associated with this Action - only populated by the  runtime getRecommendations operation.             
     */
    scoreValue?: number;
}
export namespace ActionBase {
    export type StatusEnum = 'Draft' | 'Active' | 'Suspended' | 'Complete';
    export const StatusEnum = {
        Draft: 'Draft' as StatusEnum,
        Active: 'Active' as StatusEnum,
        Suspended: 'Suspended' as StatusEnum,
        Complete: 'Complete' as StatusEnum
    }
}
