/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface AuthProviderTypeResponse {
    /**
     * External provider of authentication services. The 'None' provider indicates access to the REST API is not authenticated.
     */
    authProviderType?: AuthProviderTypeResponse.AuthProviderTypeEnum;
}
export namespace AuthProviderTypeResponse {
    export type AuthProviderTypeEnum = 'None' | 'Spectrum';
    export const AuthProviderTypeEnum = {
        None: 'None' as AuthProviderTypeEnum,
        Spectrum: 'Spectrum' as AuthProviderTypeEnum
    }
}
