/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ActionBase } from './actionBase';
import { Identifier } from './identifier';
import { UpdateInfo } from './updateInfo';


export interface BnaAction extends ActionBase {
    /**
     * Unique identifier for the item
     */
    id: string;
    /**
     * Date and time when entity was created
     */
    createdWhen: string;
    /**
     * Name of user who created this entity
     */
    createdBy: string;
    /**
     * Date and time when entity was last updated
     */
    updatedWhen: string;
    /**
     * Name of user who last updated this entity
     */
    updatedBy: string;
    /**
     * Effective status is calculated by the service based on status and availability dates
     */
    effectiveStatus?: BnaAction.EffectiveStatusEnum;
}
export namespace BnaAction {
    export type EffectiveStatusEnum = 'Draft' | 'Active' | 'Suspended' | 'Complete' | 'Pending';
    export const EffectiveStatusEnum = {
        Draft: 'Draft' as EffectiveStatusEnum,
        Active: 'Active' as EffectiveStatusEnum,
        Suspended: 'Suspended' as EffectiveStatusEnum,
        Complete: 'Complete' as EffectiveStatusEnum,
        Pending: 'Pending' as EffectiveStatusEnum
    }
}
