/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ChannelBase } from './channelBase';


export interface ChannelUpdate extends ChannelBase {
    /**
     * Date and time when entity was last updated. This must be the same timestamp as when the entity was feteched. The service will check this timestamp against the current timestamp on the entity and the operation will fail with a conflict error if they are different.
     */
    updatedWhen: string;
}
