/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ChannelBase } from './channelBase';
import { Identifier } from './identifier';


export interface Channel extends Identifier {
    /**
     * String suitable for display to a user.
     */
    name: string;
    /**
     * Description of the item and its purpose.
     */
    description?: string;
    /**
     * ID of the Domain in which the item exists.
     */
    domainId?: string;
    /**
     * Date and time when entity was created
     */
    createdWhen: string;
    /**
     * Name of user who created this entity
     */
    createdBy: string;
    /**
     * Date and time when entity was last updated
     */
    updatedWhen: string;
    /**
     * Name of user who last updated this entity
     */
    updatedBy: string;
}
