/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ComparatorArguments } from './comparatorArguments';


/**
 * Definition of a comparison operator
 */
export interface Comparator {
    /**
     * System name of the comparator
     */
    name?: string;
    /**
     * The name to be displayed to the user
     */
    displayName?: string;
    /**
     * Each object in the array represents one argument to the comparator.
     */
    arguments?: Array<ComparatorArguments>;
}
