/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Field } from './field';
import { ItemBase } from './itemBase';


export interface EntityDefinition extends ItemBase {
    fields?: Field;
    /**
     * Metadata definition. JSON object representing a JSON schema.
     */
    definition?: any;
}
