/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { NameValuePair } from './nameValuePair';


export interface ErrorResponse {
    /**
     * A URI that indicates the reason for the error.
     */
    type: string;
    /**
     * Short, localised, human-readable summary of the problem.
     */
    title: string;
    /**
     * The HTTP status code generated by the origin server. It is included here because the HTTP status code might be changed by proxies, etc.  
     */
    status: string;
    /**
     * A human-readable explanation of the problem, not localised.  Primarily intended for developers who need to debug the problem 
     */
    detail?: string;
    /**
     * Optional URI that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * Collection of name-value pairs. Populated only for certain types of error.
     */
    additionalData?: Array<NameValuePair>;
}
