/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface Field {
    /**
     * Field name
     */
    name?: string;
    /**
     * Fully qualified path to this field, starting from the root.
     */
    path?: string;
    /**
     * Type of the field
     */
    type?: Field.TypeEnum;
    /**
     * Descripton of the field
     */
    description?: string;
    /**
     * Indicates whether this field contains a collection of values.
     */
    isCollection?: boolean;
    /**
     * Indicates whether this field must be present in instances of this type of object.
     */
    isRequired?: boolean;
    /**
     * If the field is of type enum, the options array holds the list of possible values.
     */
    options?: Array<string>;
    /**
     * Collection of child fields, only populated if this field is of type object.
     */
    fields?: Array<Field>;
}
export namespace Field {
    export type TypeEnum = 'integer' | 'number' | 'string' | 'boolean' | 'datetime' | 'enum' | 'object';
    export const TypeEnum = {
        Integer: 'integer' as TypeEnum,
        Number: 'number' as TypeEnum,
        String: 'string' as TypeEnum,
        Boolean: 'boolean' as TypeEnum,
        Datetime: 'datetime' as TypeEnum,
        Enum: 'enum' as TypeEnum,
        Object: 'object' as TypeEnum
    }
}
