/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Aggregator } from './aggregator';
import { Comparator } from './comparator';


/**
 * Group of operators for a specified data type
 */
export interface OperatorGroup {
    /**
     * Collection of comparison operators for this data type
     */
    comparators?: Array<Comparator>;
    /**
     * Collection of aggregation operators for this data type
     */
    aggregators?: Array<Aggregator>;
}
