/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OperatorGroup } from './operatorGroup';


/**
 * Set of operator definitions - each field contains operators for a single data type
 */
export interface OperatorsOperatorGroups {
    string?: OperatorGroup;
    integer?: OperatorGroup;
    number?: OperatorGroup;
    boolean?: OperatorGroup;
    datetime?: OperatorGroup;
    collection?: OperatorGroup;
    enum?: OperatorGroup;
}
