/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OperatorEnum } from './operatorEnum';
import { OperatorsOperatorGroups } from './operatorsOperatorGroups';


/**
 * Represents the collection of available operators for one or more data types
 */
export interface Operators {
    /**
     * Collection of enum data types
     */
    enums?: Array<OperatorEnum>;
    operatorGroups?: OperatorsOperatorGroups;
}
