/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OperatorEnumValues } from './operatorEnumValues';


/**
 * Contains the set of allowable values for a specified enumeration
 */
export interface OperatorEnum {
    /**
     * Name of the enumeration (which is considered to be a new data type)
     */
    datatype?: string;
    /**
     * Collection of values for the enumeration
     */
    values?: Array<OperatorEnumValues>;
}
