/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface Paging {
    /**
     * Number of the items skipped before the start of the results.
     */
    offset: number;
    /**
     * Maximum number of items requested.
     */
    limit: number;
    /**
     * Number of items returned.
     */
    count?: number;
    /**
     * Total number of items available.
     */
    total: number;
}
