/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RecommendationContext } from './recommendationContext';
import { RequestProperties } from './requestProperties';


export interface RecommendationRequest {
    context: RecommendationContext;
    /**
     * Unique identifier for the subject on behalf of which the recommendations are generated
     */
    subjectIdentifier: string;
    /**
     * Name of the external system for which the subject identifier is valid. If not supplied, the default system is assumed.
     */
    system?: string;
    /**
     * Optional object containing some or all of the data fields defined by the Subject Metadata associated with the domain.
     */
    subject?: any;
    /**
     * Maximum number of recommendations to return
     */
    maxResults?: number;
    properties?: RequestProperties;
}
