/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface RecommendationContext {
    /**
     * Name of the Domain that contains the recommendations
     */
    domainName: string;
    /**
     * Name of the communication channel on which the request is made. A set of Channels is configured per Domain and may be different across domains.
     */
    channel: string;
    /**
     * Optional - Identifier for an intermediary such as an Agent who is dealing with the Subject (customer)
     */
    agent?: string;
    /**
     * Optional - Identifier for the application or system that is making the request
     */
    application?: string;
    /**
     * Optional - Type of activity in which the user is enganged when the request is made.  Examples might include Purchase, Complaint, Renewal, etc.  A set of Activities is configured per Tenant and may be different across Tenants. 
     */
    activity?: string;
    /**
     * Optional - Physical location of the user at the time that the request is made. Note - detail of the format to be confirmed.  
     */
    location?: string;
    /**
     * Optional - Locale in which the requester is working. If suppplied, this value overrides any value supplied in a header. 
     */
    locale?: string;
    /**
     * Optional - Timezone in which the requester is operating. Note - Format to be confirmed. 
     */
    timezone?: string;
    /**
     * Optional - An identifier that is meaningful to an external system for the purpose of grouping requests
     */
    conversationId?: string;
    /**
     * Optional - Name of a Strategy to be used when calculating Recommendations. A Domain can have multiple Strategies defined. If the supplied name matches a Strategy name in the Domain then it will be used. If there is no match or if no Strategy is supplied, the default Strategy will be used. 
     */
    strategy?: string;
}
