/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TreatmentHistory } from './treatmentHistory';


export interface RequestHistory {
    /**
     * Unique identifier for the request that resulted in this treatment
     */
    requestId?: number;
    /**
     * Time at which the Request was made
     */
    requestTimestamp?: string;
    /**
     * Name of the Domain through which the Request was made
     */
    domainName?: string;
    /**
     * Name of the Channel on which the Treatment was made
     */
    channelName?: string;
    /**
     * Identifier for a conversation (which groups together potentially many Requests and treatments)
     */
    conversation?: string;
    /**
     * Identifier for the Agent (if any) in an assisted channel
     */
    agent?: string;
    /**
     * Name of the Application making the request
     */
    application?: string;
    /**
     * Activity that the Subject was undertaking when the request was made
     */
    activity?: string;
    /**
     * The Subject's location (if known) at the time the request was made
     */
    location?: string;
    /**
     * The Subject's locale
     */
    locale?: string;
    /**
     * The Subject's timezone
     */
    timezone?: string;
    /**
     * The Strategy (if any) that was specified in the Request
     */
    strategy?: string;
    /**
     * The maximum number of results, if it was specified in the Request
     */
    maxResult?: string;
    treatments?: Array<TreatmentHistory>;
}
