/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ResponseHistory {
    /**
     * Unique identifier for the Response (if any)
     */
    responseId?: number;
    /**
     * Time at which the Response was received
     */
    responseTimestamp?: string;
    /**
     * Identifier for the type of response receieved
     */
    responseTypeId?: string;
    /**
     * Display name of the response type
     */
    responseTypeName?: string;
    /**
     * Category of response (-1, 0, 1)
     */
    responseCategory?: number;
    /**
     * Date and time until which this type of Action will be suppressed
     */
    suppressUntil?: string;
}
