/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface SelectionUsageBase {
    /**
     * ID of the Selection
     */
    selectionId: string;
    /**
     * ID of the Action. Mutually exclusive with tagId.
     */
    actionId?: string;
    /**
     * ID of an Action Tag. Mutually exclusive with actionId.
     */
    tagId?: string;
}
