/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Identifier } from './identifier';
import { ItemSummary } from './itemSummary';
import { SelectionUsageBase } from './selectionUsageBase';


export interface SelectionUsage extends SelectionUsageBase {
    /**
     * Unique identifier for the item
     */
    id: string;
    /**
     * Name of the Selection
     */
    selectionName?: string;
    /**
     * Name of the Action. Only populated where a Selection Usage is directly associated with an Action.
     */
    actionName?: string;
    /**
     * Name of the Action Tag. Only populated where a Selection Usage is associated with an Action Tag instead of an Action instance.
     */
    tagName?: string;
    /**
     * Collection of Actions that are associated with the Tag.  For example, this might be all Sales campaigns. This collection is only present if a Selection Id was passed as a parameter and if the Selection Usage is associated with a Tag. 
     */
    actions?: Array<ItemSummary>;
}
