/**
 * Best Next Action API
 * APIs for Best Next Action capabilities.   Note that the error specification used by this API is based  on the IETF draft: https://tools.ietf.org/html/rfc7807 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DomainId } from './domainId';
import { ItemBase } from './itemBase';


export interface StrategyBase extends ItemBase {
    /**
     * ID of the Domain in which the item exists.
     */
    domainId?: string;
    /**
     * JSON object representing the logic that defines the strategy. 
     */
    logic?: any;
    /**
     * Type of logic represented by the logic property. This property specifies how the content of the logic should be interpreted. This enables the potential use of multiple logic execution engines.  If empty, the default logic processing engine will be used.  
     */
    logicType?: string;
    /**
     * Whether or not the strategy is in use. If omitted, the strategy is created with a false isActive property 
     */
    isActive?: boolean;
}
